FROM ubuntu:latest

# Update and install dependencies
RUN apt-get -y update \
    && apt-get -y upgrade \
    && apt-get -y install git python3-pip

# Install project requirements
WORKDIR /home/app
RUN pip3 install -r requirements.txt